language:      ruby
rvm:
  - 2.6.5
sudo: false
git:
  depth:       3
node_js:
  - "node"
install:       npm install
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
  - bundle install --path=~/.bundle
  - bundle exec jekyll build
  - bundle exec htmlproofer --empty_alt_ignore --url-ignore "/^#$/" --disable_external ./_site
cache:
  directories:
    - node_modules
    - ~/.bundle
notifications:
  email:       false
