language:      ruby
rvm:
  - 2.6.5
sudo: false
git:
  depth:       3
node_js:
  - "node"
install:       npm install
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
  - bundle install --path=~/.bundle
  - bundle exec jekyll build
  - bundle exec htmlproofer --empty_alt_ignore --url-ignore "/^#$/" --report-invalid-tags --internal-domains jekyll-aws.s3-website-ap-northeast-1.amazonaws.com --report-missing-names --report-script-embeds --report-missing-doctype --check-html --assume-extension --log-level debug ./_site
cache:
  directories:
    - node_modules
    - ~/.bundle
notifications:
  email:       false
